# Base tests we can run on every commit/PR/etc
#
# Thanks to Nix caching, this will only run tests for components that
# have changed since previous successful runs.
name: Core Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v15

      - name: Cachix
        uses: cachix/cachix-action@v10
        with:
          name: theta-idl
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Theta
        run: nix build .#theta

      - name: Cross-Language Tests
        run: nix build .#test
