# Additional tests run on merge into stage
name: Stage Tests

on:
  push:
    branches:
      - 'stage'

jobs:
  stack-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v15

      - name: Cachix
        uses: cachix/cachix-action@v10
        with:
          name: theta-idl
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Cache Stack Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('theta/stack.yaml.lock', 'theta/theta.cabal') }}

      - name: Stack Test
        run: ci/stack-test ./theta
